#pragma once

#include <ble/core/ble_defs.h>

#define CFG_TX_POWER (0x19)

#define CFG_IDENTITY_ADDRESS GAP_PUBLIC_ADDR

#define CFG_ENCRYPTION_KEY_SIZE_MAX (16)
#define CFG_ENCRYPTION_KEY_SIZE_MIN (8)

#define CFG_IO_CAPABILITY IO_CAP_DISPLAY_YES_NO

#define CFG_SC_SUPPORT SC_PAIRING_OPTIONAL

#define ALL_PHYS_PREFERENCE 0x00
#define RX_2M_PREFERRED     0x02
#define TX_2M_PREFERRED     0x02
#define TX_1M               0x01
#define TX_2M               0x02
#define RX_1M               0x01
#define RX_2M               0x02

#define CFG_BLE_NUM_LINK 2

#define CFG_BLE_NUM_GATT_SERVICES 8

#define CFG_BLE_NUM_GATT_ATTRIBUTES 68

#define CFG_BLE_MAX_ATT_MTU (256 + 128 + 16 + 8 + 4 + 2)

#define CFG_BLE_ATT_VALUE_ARRAY_SIZE (1344 + 256)

#define CFG_BLE_PREPARE_WRITE_LIST_SIZE BLE_PREP_WRITE_X_ATT(CFG_BLE_MAX_ATT_MTU)

#define CFG_BLE_MBLOCK_COUNT \
    (BLE_MBLOCKS_CALC(CFG_BLE_PREPARE_WRITE_LIST_SIZE, CFG_BLE_MAX_ATT_MTU, CFG_BLE_NUM_LINK))

#define CFG_BLE_DATA_LENGTH_EXTENSION 1

#define CFG_BLE_SLAVE_SCA 500

#define CFG_BLE_MASTER_SCA 0

#define CFG_BLE_LSE_SOURCE                                                        \
    SHCI_C2_BLE_INIT_CFG_BLE_LS_CLK_LSE | SHCI_C2_BLE_INIT_CFG_BLE_LS_OTHER_DEV | \
        SHCI_C2_BLE_INIT_CFG_BLE_LS_CALIB

#define CFG_BLE_HSE_STARTUP_TIME 0x148

#define CFG_BLE_MAX_CONN_EVENT_LENGTH (0xFFFFFFFF)

#define CFG_BLE_VITERBI_MODE 1

#define CFG_BLE_OPTIONS                                                                 \
    (SHCI_C2_BLE_INIT_OPTIONS_LL_HOST | SHCI_C2_BLE_INIT_OPTIONS_WITH_SVC_CHANGE_DESC | \
     SHCI_C2_BLE_INIT_OPTIONS_DEVICE_NAME_RO | SHCI_C2_BLE_INIT_OPTIONS_EXT_ADV |       \
     SHCI_C2_BLE_INIT_OPTIONS_CS_ALGO2 | SHCI_C2_BLE_INIT_OPTIONS_POWER_CLASS_2_3)

#define CFG_TLBLE_EVT_QUEUE_LENGTH 5

#define CFG_TLBLE_MOST_EVENT_PAYLOAD_SIZE \
    255

#define TL_BLE_EVENT_FRAME_SIZE (TL_EVT_HDR_SIZE + CFG_TLBLE_MOST_EVENT_PAYLOAD_SIZE)

#define CFG_DEBUG_TRACE_FULL  0
#define CFG_DEBUG_TRACE_LIGHT 0
