#pragma once

#define CFG_HW_PWR_STANDBY_SEMID     10

#define CFG_HW_THREAD_NVM_SRAM_SEMID 9

#define CFG_HW_BLE_NVM_SRAM_SEMID 8

#define CFG_HW_BLOCK_FLASH_REQ_BY_CPU2_SEMID 7

#define CFG_HW_BLOCK_FLASH_REQ_BY_CPU1_SEMID 6

#define CFG_HW_CLK48_CONFIG_SEMID 5

#define CFG_HW_ENTRY_STOP_MODE_SEMID 4

#define CFG_HW_RCC_SEMID 3

#define CFG_HW_FLASH_SEMID 2

#define CFG_HW_PKA_SEMID 1

#define CFG_HW_RNG_SEMID 0
