@echo off
setlocal enabledelayedexpansion
chcp 65001 >nul

cd /d "%~dp0.."

:MENU
echo.
echo ===================================================
echo  FBT SHORTCUT MENU
echo ===================================================
echo.
echo  [1] Clean Workspace + Generate TGZ ^& DFU [updater_package]
echo  [2] Clean Workspace + Flash Live USB [flash_usb_full]
echo  [3] Native Fast Compilation Pass Only [fbt]
echo  [4] Min-Package (DFU ONLY) [fbt updater_minpackage]
echo  [5] Run fbt -c
echo  [6] Delete Build, Dist, ^& scons.dblite
echo  [7] Delete Build, Dist, ^& scons.dblite + run fbt -c
echo.
echo  [8] Exit FBT Shortcut Menu
echo.
echo ===================================================
echo.

:: Capture character keys instantly without pressing Enter
choice /c 12345678 /n /m "Enter Selection: "
echo.

if errorlevel 8 goto CMD_EXIT
if errorlevel 7 goto CLEAN_FBT
if errorlevel 6 goto JUST_CLEAN
if errorlevel 5 goto FBT_C
if errorlevel 4 goto MINPKG
if errorlevel 3 goto JUSTFBT
if errorlevel 2 goto LVEUSB
if errorlevel 1 goto UPDPKG

:LVEUSB
echo ===================================================
echo CLEANING WORKSPACE AND LAUNCHING LIVE USB FLASH...
echo ===================================================
if exist build rmdir /s /q build
if exist dist rmdir /s /q dist
if exist .sconsign.dblite del /f /q .sconsign.dblite
call fbt -c

:LOOP_LVEUSB
echo Running live USB flash...

:: Stream fbt output live, tee it to a log file for size parsing, set flag on
:: Permission/Denied, restart if Error seen after flag is set
powershell -Command "$flag=$false; $restart=$false; cmd.exe /c fbt flash_usb_full COMPACT=1 DEBUG=0 FORCE=1 2>&1 | Tee-Object -FilePath 'fbt_build_output.tmp.log' | ForEach-Object { Write-Host $_; if ($_ -match '(?i)permission|(?i)denied') { $flag=$true }; if ($_ -match '(?i)error' -and $flag) { $restart=$true } }; if ($restart) { exit 0 } else { exit 1 }"
if %errorlevel%==0 (
 echo.
 echo Permission/Denied + Error detected! Retrying command...
 echo.
 goto LOOP_LVEUSB
)

call :SIZE_REPORT

echo.
:LOOP_LVEUSB_WAITENTER
if defined RETRY_LOOP_LVEUSB (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIAAkAGsAIAA9ACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AUgBlAGEAZABLAGUAeQAoACcATgBvAEUAYwBoAG8ALABJAG4AYwBsAHUAZABlAEsAZQB5AEQAbwB3AG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAawAuAFYAaQByAHQAdQBhAGwASwBlAHkAQwBvAGQAZQAgAC0AZQBxACAAMQAzACkAIAB7ACAAYgByAGUAYQBrACAAfQAKAH0ACgB0AHIAeQAgAHsAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAZgBhAGwAcwBlACAAfQAgAGMAYQB0AGMAaAAgAHsAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBlAHgAaQB0ACAAMAAKAA==
) else (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAE4AbwBOAGUAdwBsAGkAbgBlACAAJwBQAHIAZQBzAHMAIABFAE4AVABFAFIAIAB0AG8AIAByAGUAdAB1AHIAbgAgAHQAbwAgAE0AYQBzAHQAZQByACAATQBlAG4AdQAuAC4ALgAnAAoAdwBoAGkAbABlACAAKAAkAHQAcgB1AGUAKQAgAHsACgAgACAAIAAgACQAawAgAD0AIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBSAGUAYQBkAEsAZQB5ACgAJwBOAG8ARQBjAGgAbwAsAEkAbgBjAGwAdQBkAGUASwBlAHkARABvAHcAbgAnACkACgAgACAAIAAgAGkAZgAgACgAJABrAC4AVgBpAHIAdAB1AGEAbABLAGUAeQBDAG8AZABlACAALQBlAHEAIAAxADMAKQAgAHsAIABiAHIAZQBhAGsAIAB9AAoAfQAKAHQAcgB5ACAAewAgAFsAQwBvAG4AcwBvAGwAZQBdADoAOgBUAHIAZQBhAHQAQwBvAG4AdAByAG8AbABDAEEAcwBJAG4AcAB1AHQAIAA9ACAAJABmAGEAbABzAGUAIAB9ACAAYwBhAHQAYwBoACAAewB9AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAGUAeABpAHQAIAAwAAoA
)
if not "%errorlevel%"=="0" (
    set "RETRY_LOOP_LVEUSB=1"
    goto LOOP_LVEUSB_WAITENTER
)
set "RETRY_LOOP_LVEUSB="
goto MENU

:UPDPKG
echo ===================================================
echo CLEANING WORKSPACE AND GENERATING UPDATER PACKAGE...
echo ===================================================
if exist build rmdir /s /q build
if exist dist rmdir /s /q dist
if exist .sconsign.dblite del /f /q .sconsign.dblite
call fbt -c

:LOOP_UPDPKG
echo Running updater package...

:: Stream fbt output live, tee it to a log file for size parsing, set flag on
:: Permission/Denied, restart if Error seen after flag is set
powershell -Command "$flag=$false; $restart=$false; cmd.exe /c fbt updater_package COMPACT=1 DEBUG=0 FORCE=1 2>&1 | Tee-Object -FilePath 'fbt_build_output.tmp.log' | ForEach-Object { Write-Host $_; if ($_ -match '(?i)permission|(?i)denied') { $flag=$true }; if ($_ -match '(?i)error' -and $flag) { $restart=$true } }; if ($restart) { exit 0 } else { exit 1 }"
if %errorlevel%==0 (
 echo.
 echo Permission/Denied + Error detected! Retrying command...
 echo.
 goto LOOP_UPDPKG
)

call :SIZE_REPORT

echo.
:LOOP_UPDPKG_WAITENTER
if defined RETRY_LOOP_UPDPKG (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIAAkAGsAIAA9ACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AUgBlAGEAZABLAGUAeQAoACcATgBvAEUAYwBoAG8ALABJAG4AYwBsAHUAZABlAEsAZQB5AEQAbwB3AG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAawAuAFYAaQByAHQAdQBhAGwASwBlAHkAQwBvAGQAZQAgAC0AZQBxACAAMQAzACkAIAB7ACAAYgByAGUAYQBrACAAfQAKAH0ACgB0AHIAeQAgAHsAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAZgBhAGwAcwBlACAAfQAgAGMAYQB0AGMAaAAgAHsAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBlAHgAaQB0ACAAMAAKAA==
) else (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAE4AbwBOAGUAdwBsAGkAbgBlACAAJwBQAHIAZQBzAHMAIABFAE4AVABFAFIAIAB0AG8AIAByAGUAdAB1AHIAbgAgAHQAbwAgAE0AYQBzAHQAZQByACAATQBlAG4AdQAuAC4ALgAnAAoAdwBoAGkAbABlACAAKAAkAHQAcgB1AGUAKQAgAHsACgAgACAAIAAgACQAawAgAD0AIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBSAGUAYQBkAEsAZQB5ACgAJwBOAG8ARQBjAGgAbwAsAEkAbgBjAGwAdQBkAGUASwBlAHkARABvAHcAbgAnACkACgAgACAAIAAgAGkAZgAgACgAJABrAC4AVgBpAHIAdAB1AGEAbABLAGUAeQBDAG8AZABlACAALQBlAHEAIAAxADMAKQAgAHsAIABiAHIAZQBhAGsAIAB9AAoAfQAKAHQAcgB5ACAAewAgAFsAQwBvAG4AcwBvAGwAZQBdADoAOgBUAHIAZQBhAHQAQwBvAG4AdAByAG8AbABDAEEAcwBJAG4AcAB1AHQAIAA9ACAAJABmAGEAbABzAGUAIAB9ACAAYwBhAHQAYwBoACAAewB9AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAGUAeABpAHQAIAAwAAoA
)
if not "%errorlevel%"=="0" (
    set "RETRY_LOOP_UPDPKG=1"
    goto LOOP_UPDPKG_WAITENTER
)
set "RETRY_LOOP_UPDPKG="
goto MENU

:FBT_C
echo ===================================================
echo RUNNING FBT CLEAN (-c)...
echo ===================================================
call fbt -c
echo.
:FBT_C_WAITENTER
if defined RETRY_FBT_C (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIAAkAGsAIAA9ACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AUgBlAGEAZABLAGUAeQAoACcATgBvAEUAYwBoAG8ALABJAG4AYwBsAHUAZABlAEsAZQB5AEQAbwB3AG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAawAuAFYAaQByAHQAdQBhAGwASwBlAHkAQwBvAGQAZQAgAC0AZQBxACAAMQAzACkAIAB7ACAAYgByAGUAYQBrACAAfQAKAH0ACgB0AHIAeQAgAHsAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAZgBhAGwAcwBlACAAfQAgAGMAYQB0AGMAaAAgAHsAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBlAHgAaQB0ACAAMAAKAA==
) else (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAE4AbwBOAGUAdwBsAGkAbgBlACAAJwBQAHIAZQBzAHMAIABFAE4AVABFAFIAIAB0AG8AIAByAGUAdAB1AHIAbgAgAHQAbwAgAE0AYQBzAHQAZQByACAATQBlAG4AdQAuAC4ALgAnAAoAdwBoAGkAbABlACAAKAAkAHQAcgB1AGUAKQAgAHsACgAgACAAIAAgACQAawAgAD0AIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBSAGUAYQBkAEsAZQB5ACgAJwBOAG8ARQBjAGgAbwAsAEkAbgBjAGwAdQBkAGUASwBlAHkARABvAHcAbgAnACkACgAgACAAIAAgAGkAZgAgACgAJABrAC4AVgBpAHIAdAB1AGEAbABLAGUAeQBDAG8AZABlACAALQBlAHEAIAAxADMAKQAgAHsAIABiAHIAZQBhAGsAIAB9AAoAfQAKAHQAcgB5ACAAewAgAFsAQwBvAG4AcwBvAGwAZQBdADoAOgBUAHIAZQBhAHQAQwBvAG4AdAByAG8AbABDAEEAcwBJAG4AcAB1AHQAIAA9ACAAJABmAGEAbABzAGUAIAB9ACAAYwBhAHQAYwBoACAAewB9AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAGUAeABpAHQAIAAwAAoA
)
if not "%errorlevel%"=="0" (
    set "RETRY_FBT_C=1"
    goto FBT_C_WAITENTER
)
set "RETRY_FBT_C="
goto MENU

:JUST_CLEAN
echo ===================================================
echo DELETING BUILD, DIST, AND SCONS.DBLITE...
echo ===================================================
if exist build rmdir /s /q build
if exist dist rmdir /s /q dist
if exist .sconsign.dblite del /f /q .sconsign.dblite
echo Done.
echo.
:JUST_CLEAN_WAITENTER
if defined RETRY_JUST_CLEAN (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIAAkAGsAIAA9ACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AUgBlAGEAZABLAGUAeQAoACcATgBvAEUAYwBoAG8ALABJAG4AYwBsAHUAZABlAEsAZQB5AEQAbwB3AG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAawAuAFYAaQByAHQAdQBhAGwASwBlAHkAQwBvAGQAZQAgAC0AZQBxACAAMQAzACkAIAB7ACAAYgByAGUAYQBrACAAfQAKAH0ACgB0AHIAeQAgAHsAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAZgBhAGwAcwBlACAAfQAgAGMAYQB0AGMAaAAgAHsAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBlAHgAaQB0ACAAMAAKAA==
) else (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAE4AbwBOAGUAdwBsAGkAbgBlACAAJwBQAHIAZQBzAHMAIABFAE4AVABFAFIAIAB0AG8AIAByAGUAdAB1AHIAbgAgAHQAbwAgAE0AYQBzAHQAZQByACAATQBlAG4AdQAuAC4ALgAnAAoAdwBoAGkAbABlACAAKAAkAHQAcgB1AGUAKQAgAHsACgAgACAAIAAgACQAawAgAD0AIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBSAGUAYQBkAEsAZQB5ACgAJwBOAG8ARQBjAGgAbwAsAEkAbgBjAGwAdQBkAGUASwBlAHkARABvAHcAbgAnACkACgAgACAAIAAgAGkAZgAgACgAJABrAC4AVgBpAHIAdAB1AGEAbABLAGUAeQBDAG8AZABlACAALQBlAHEAIAAxADMAKQAgAHsAIABiAHIAZQBhAGsAIAB9AAoAfQAKAHQAcgB5ACAAewAgAFsAQwBvAG4AcwBvAGwAZQBdADoAOgBUAHIAZQBhAHQAQwBvAG4AdAByAG8AbABDAEEAcwBJAG4AcAB1AHQAIAA9ACAAJABmAGEAbABzAGUAIAB9ACAAYwBhAHQAYwBoACAAewB9AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAGUAeABpAHQAIAAwAAoA
)
if not "%errorlevel%"=="0" (
    set "RETRY_JUST_CLEAN=1"
    goto JUST_CLEAN_WAITENTER
)
set "RETRY_JUST_CLEAN="
goto MENU

:CLEAN_FBT
echo ===================================================
echo DELETING FILES AND RUNNING FBT CLEAN...
echo ===================================================
if exist build rmdir /s /q build
if exist dist rmdir /s /q dist
if exist .sconsign.dblite del /f /q .sconsign.dblite
call fbt -c
echo.
:CLEAN_FBT_WAITENTER
if defined RETRY_CLEAN_FBT (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIAAkAGsAIAA9ACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AUgBlAGEAZABLAGUAeQAoACcATgBvAEUAYwBoAG8ALABJAG4AYwBsAHUAZABlAEsAZQB5AEQAbwB3AG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAawAuAFYAaQByAHQAdQBhAGwASwBlAHkAQwBvAGQAZQAgAC0AZQBxACAAMQAzACkAIAB7ACAAYgByAGUAYQBrACAAfQAKAH0ACgB0AHIAeQAgAHsAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAZgBhAGwAcwBlACAAfQAgAGMAYQB0AGMAaAAgAHsAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBlAHgAaQB0ACAAMAAKAA==
) else (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAE4AbwBOAGUAdwBsAGkAbgBlACAAJwBQAHIAZQBzAHMAIABFAE4AVABFAFIAIAB0AG8AIAByAGUAdAB1AHIAbgAgAHQAbwAgAE0AYQBzAHQAZQByACAATQBlAG4AdQAuAC4ALgAnAAoAdwBoAGkAbABlACAAKAAkAHQAcgB1AGUAKQAgAHsACgAgACAAIAAgACQAawAgAD0AIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBSAGUAYQBkAEsAZQB5ACgAJwBOAG8ARQBjAGgAbwAsAEkAbgBjAGwAdQBkAGUASwBlAHkARABvAHcAbgAnACkACgAgACAAIAAgAGkAZgAgACgAJABrAC4AVgBpAHIAdAB1AGEAbABLAGUAeQBDAG8AZABlACAALQBlAHEAIAAxADMAKQAgAHsAIABiAHIAZQBhAGsAIAB9AAoAfQAKAHQAcgB5ACAAewAgAFsAQwBvAG4AcwBvAGwAZQBdADoAOgBUAHIAZQBhAHQAQwBvAG4AdAByAG8AbABDAEEAcwBJAG4AcAB1AHQAIAA9ACAAJABmAGEAbABzAGUAIAB9ACAAYwBhAHQAYwBoACAAewB9AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAGUAeABpAHQAIAAwAAoA
)
if not "%errorlevel%"=="0" (
    set "RETRY_CLEAN_FBT=1"
    goto CLEAN_FBT_WAITENTER
)
set "RETRY_CLEAN_FBT="
goto MENU

:JUSTFBT
echo ===================================================
echo LAUNCHING NATIVE FAST COMPILATION PASS ONLY...
echo ===================================================
powershell -Command "cmd.exe /c fbt 2>&1 | Tee-Object -FilePath 'fbt_build_output.tmp.log' | ForEach-Object { Write-Host $_ }"

call :SIZE_REPORT

echo.
:JUSTFBT_WAITENTER
if defined RETRY_JUSTFBT (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIAAkAGsAIAA9ACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AUgBlAGEAZABLAGUAeQAoACcATgBvAEUAYwBoAG8ALABJAG4AYwBsAHUAZABlAEsAZQB5AEQAbwB3AG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAawAuAFYAaQByAHQAdQBhAGwASwBlAHkAQwBvAGQAZQAgAC0AZQBxACAAMQAzACkAIAB7ACAAYgByAGUAYQBrACAAfQAKAH0ACgB0AHIAeQAgAHsAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAZgBhAGwAcwBlACAAfQAgAGMAYQB0AGMAaAAgAHsAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBlAHgAaQB0ACAAMAAKAA==
) else (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAE4AbwBOAGUAdwBsAGkAbgBlACAAJwBQAHIAZQBzAHMAIABFAE4AVABFAFIAIAB0AG8AIAByAGUAdAB1AHIAbgAgAHQAbwAgAE0AYQBzAHQAZQByACAATQBlAG4AdQAuAC4ALgAnAAoAdwBoAGkAbABlACAAKAAkAHQAcgB1AGUAKQAgAHsACgAgACAAIAAgACQAawAgAD0AIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBSAGUAYQBkAEsAZQB5ACgAJwBOAG8ARQBjAGgAbwAsAEkAbgBjAGwAdQBkAGUASwBlAHkARABvAHcAbgAnACkACgAgACAAIAAgAGkAZgAgACgAJABrAC4AVgBpAHIAdAB1AGEAbABLAGUAeQBDAG8AZABlACAALQBlAHEAIAAxADMAKQAgAHsAIABiAHIAZQBhAGsAIAB9AAoAfQAKAHQAcgB5ACAAewAgAFsAQwBvAG4AcwBvAGwAZQBdADoAOgBUAHIAZQBhAHQAQwBvAG4AdAByAG8AbABDAEEAcwBJAG4AcAB1AHQAIAA9ACAAJABmAGEAbABzAGUAIAB9ACAAYwBhAHQAYwBoACAAewB9AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAGUAeABpAHQAIAAwAAoA
)
if not "%errorlevel%"=="0" (
    set "RETRY_JUSTFBT=1"
    goto JUSTFBT_WAITENTER
)
set "RETRY_JUSTFBT="
goto MENU

:MINPKG
echo ===================================================
echo RUNNING MIN-PACKAGE (DFU ONLY)...
echo ===================================================
powershell -Command "cmd.exe /c fbt updater_minpackage 2>&1 | Tee-Object -FilePath 'fbt_build_output.tmp.log' | ForEach-Object { Write-Host $_ }"

call :SIZE_REPORT

echo.
:MINPKG_WAITENTER
if defined RETRY_MINPKG (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIAAkAGsAIAA9ACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AUgBlAGEAZABLAGUAeQAoACcATgBvAEUAYwBoAG8ALABJAG4AYwBsAHUAZABlAEsAZQB5AEQAbwB3AG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAawAuAFYAaQByAHQAdQBhAGwASwBlAHkAQwBvAGQAZQAgAC0AZQBxACAAMQAzACkAIAB7ACAAYgByAGUAYQBrACAAfQAKAH0ACgB0AHIAeQAgAHsAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAZgBhAGwAcwBlACAAfQAgAGMAYQB0AGMAaAAgAHsAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBlAHgAaQB0ACAAMAAKAA==
) else (
    powershell -NoProfile -EncodedCommand dAByAHkAIAB7AAoAIAAgACAAIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoAVAByAGUAYQB0AEMAbwBuAHQAcgBvAGwAQwBBAHMASQBuAHAAdQB0ACAAPQAgACQAdAByAHUAZQAKAH0AIABjAGEAdABjAGgAIAB7AH0ACgAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBGAGwAdQBzAGgASQBuAHAAdQB0AEIAdQBmAGYAZQByACgAKQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAE4AbwBOAGUAdwBsAGkAbgBlACAAJwBQAHIAZQBzAHMAIABFAE4AVABFAFIAIAB0AG8AIAByAGUAdAB1AHIAbgAgAHQAbwAgAE0AYQBzAHQAZQByACAATQBlAG4AdQAuAC4ALgAnAAoAdwBoAGkAbABlACAAKAAkAHQAcgB1AGUAKQAgAHsACgAgACAAIAAgACQAawAgAD0AIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBSAGUAYQBkAEsAZQB5ACgAJwBOAG8ARQBjAGgAbwAsAEkAbgBjAGwAdQBkAGUASwBlAHkARABvAHcAbgAnACkACgAgACAAIAAgAGkAZgAgACgAJABrAC4AVgBpAHIAdAB1AGEAbABLAGUAeQBDAG8AZABlACAALQBlAHEAIAAxADMAKQAgAHsAIABiAHIAZQBhAGsAIAB9AAoAfQAKAHQAcgB5ACAAewAgAFsAQwBvAG4AcwBvAGwAZQBdADoAOgBUAHIAZQBhAHQAQwBvAG4AdAByAG8AbABDAEEAcwBJAG4AcAB1AHQAIAA9ACAAJABmAGEAbABzAGUAIAB9ACAAYwBhAHQAYwBoACAAewB9AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAGUAeABpAHQAIAAwAAoA
)
if not "%errorlevel%"=="0" (
    set "RETRY_MINPKG=1"
    goto MINPKG_WAITENTER
)
set "RETRY_MINPKG="
goto MENU

:CMD_EXIT
echo Exiting...
exit /b

:: =====================================================================
:: SIZE_REPORT - firmware size comparison report
:: Called after any option that actually compiles firmware: F (LVEUSB),
:: U (UPDPKG), N (JUSTFBT), M (MINPKG). Clean-only options (C/K/E) do not
:: call it since they never produce a "Firmware size" section.
::
:: Everything needed lives in this single .bat file: the block below
:: rebuilds a small PowerShell helper from an embedded Base64 blob,
:: decodes it to a throwaway temp script, runs it, then deletes it.
:: The helper parses fbt_build_output.tmp.log (written by the fbt
:: run above) for the "Firmware size" section. fbt can print this
:: section twice in one compile - the real firmware block (which has a
:: .free_flash line) and a second, later block that has no .free_flash
:: line. The helper uses the presence of .free_flash as the marker to
:: pick the correct block, falling back to the first complete block
:: found if no block has that marker.
:: Free flash space is computed as (0x080D7000 minus flash base
:: 0x08000000) minus (.text+.rodata+.data) - .bss is RAM only and is
:: excluded from the flash-used/free-space math (shown separately, for
:: information). The "Flash Used" row is not printed (it is just the
:: sum of .text/.rodata/.data, shown individually already); Free Space
:: is shown after its own "====" divider, on its own at the end, since
:: it is the number that matters most. Every value is shown as raw
:: bytes with thousands separators plus the KB equivalent in parens,
:: e.g. "880,640 bytes (860.00 Kb)". fbt_build_size.txt is rewritten with
:: the latest values each run; no other file is created or left behind.
:: =====================================================================
:SIZE_REPORT
if exist "%TEMP%\cbsr.b64" del /f /q "%TEMP%\cbsr.b64"
echo JABGAGwAYQBzAGgAQgBhAHMAZQAgAD0AIABbAEMAbwBuAHYAZQByAHQAXQA6ADoAVABvAEkAbgB0ADYANAAoACIAMAA4ADAAMAAwADAAMAAwACIALAAgADEANgApAAoAJABSAGEAZABpAG8AQQBkAGQAcgBlAHMAcwAgAD0AIA>>"%TEMP%\cbsr.b64"
echo BbAEMAbwBuAHYAZQByAHQAXQA6ADoAVABvAEkAbgB0ADYANAAoACIAMAA4ADAARAA3ADAAMAAwACIALAAgADEANgApAAoAJABDAGUAaQBsAGkAbgBnACAAPQAgACQAUgBhAGQAaQBvAEEAZABkAHIAZQBzAHMAIAAtACAAJABG>>"%TEMP%\cbsr.b64"
echo AGwAYQBzAGgAQgBhAHMAZQAKACQATABvAGcAUABhAHQAaAAgAD0AIAAiAC4AXABmAGIAdABfAGIAdQBpAGwAZABfAG8AdQB0AHAAdQB0AC4AdABtAHAALgBsAG8AZwAiAAoAJABEAGEAdABhAEYAaQBsAGUAIAA9ACAAIgAuAF>>"%TEMP%\cbsr.b64"
echo wAZgBiAHQAXwBiAHUAaQBsAGQAXwBzAGkAegBlAC4AdAB4AHQAIgAKAAoAaQBmACAAKAAtAG4AbwB0ACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABMAG8AZwBQAGEAdABoACkA>>"%TEMP%\cbsr.b64"
echo KQAgAHsACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAEIAdQBpAGwAZAAgAGwAbwBnACAAbgBvAHQAIABmAG8AdQBuAGQAIAAtACAAcwBrAGkAcABwAGkAbgBnACAAZgBpAHIAbQB3AGEAcgBlACAAcwBpAHoAZQ>>"%TEMP%\cbsr.b64"
echo AgAHIAZQBwAG8AcgB0AC4AIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABZAGUAbABsAG8AdwAKACAAIAAgACAAcgBlAHQAdQByAG4ACgB9AAoACgAkAGwAaQBuAGUAcwAgAD0AIABHAGUAdAAtAEMAbwBu>>"%TEMP%\cbsr.b64"
echo AHQAZQBuAHQAIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQATABvAGcAUABhAHQAaAAKACQAbgBlAGUAZABlAGQAIAA9ACAAQAAoACcAdABlAHgAdAAnACwAIAAnAHIAbwBkAGEAdABhACcALAAgACcAZABhAHQAYQAnAC>>"%TEMP%\cbsr.b64"
echo wAIAAnAGIAcwBzACcAKQAKAAoAIwAgAGYAYgB0ACAAYwBhAG4AIABwAHIAaQBuAHQAIABhACAAIgBGAGkAcgBtAHcAYQByAGUAIABzAGkAegBlACIAIABzAGUAYwB0AGkAbwBuACAAdAB3AGkAYwBlACAAaQBuACAAbwBuAGUA>>"%TEMP%\cbsr.b64"
echo IABjAG8AbQBwAGkAbABlADoAIAB0AGgAZQAgAHIAZQBhAGwACgAjACAAZgBpAHIAbQB3AGEAcgBlACAAYgB1AGkAbABkACcAcwAgAGIAbABvAGMAawAgACgAdwBoAGkAYwBoACAAaQBuAGMAbAB1AGQAZQBzACAAYQAgAC4AZg>>"%TEMP%\cbsr.b64"
echo ByAGUAZQBfAGYAbABhAHMAaAAgAGwAaQBuAGUAKQAgAGEAbgBkACAAYQAgAHMAZQBjAG8AbgBkACwACgAjACAAbABhAHQAZQByACAAYgBsAG8AYwBrACAAKABlAC4AZwAuACAAZgByAG8AbQAgAGEAIABkAGUAYgB1AGcALwB2>>"%TEMP%\cbsr.b64"
echo AGUAcgBpAGYAaQBjAGEAdABpAG8AbgAgAHAAYQBzAHMAKQAgAHQAaABhAHQAIABoAGEAcwAgAG4AbwAgAC4AZgByAGUAZQBfAGYAbABhAHMAaAAKACMAIABsAGkAbgBlAC4AIABVAHMAZQAgAHQAaABlACAAcAByAGUAcwBlAG>>"%TEMP%\cbsr.b64"
echo 4AYwBlACAAbwBmACAALgBmAHIAZQBlAF8AZgBsAGEAcwBoACAAYQBzACAAdABoAGUAIABtAGEAcgBrAGUAcgAgAHQAbwAgAHAAaQBjAGsAIAB0AGgAZQAgAHIAaQBnAGgAdAAKACMAIABiAGwAbwBjAGsALAAgAHIAYQB0AGgA>>"%TEMP%\cbsr.b64"
echo ZQByACAAdABoAGEAbgAgAGEAcwBzAHUAbQBpAG4AZwAgAGkAdAAnAHMAIABhAGwAdwBhAHkAcwAgAHQAaABlACAAZgBpAHIAcwB0ACAAKABvAHIAIABsAGEAcwB0ACkAIABvAGMAYwB1AHIAcgBlAG4AYwBlAC4ACgBmAHUAbg>>"%TEMP%\cbsr.b64"
echo BjAHQAaQBvAG4AIABHAGUAdAAtAFMAaQB6AGUAQgBsAG8AYwBrACgAJABzAHQAYQByAHQASQBkAHgALAAgACQAYQBsAGwATABpAG4AZQBzACwAIAAkAG4AZQBlAGQAZQBkAEsAZQB5AHMAKQAgAHsACgAgACAAIAAgACQAcwBp>>"%TEMP%\cbsr.b64"
echo AHoAZQBzACAAPQAgAEAAewB9AAoAIAAgACAAIAAkAGgAYQBzAEYAcgBlAGUARgBsAGEAcwBoACAAPQAgACQAZgBhAGwAcwBlAAoAIAAgACAAIAAkAGUAeAB0AHIAYQAgAD0AIAAwAAoAIAAgACAAIABmAG8AcgAgACgAJABpAC>>"%TEMP%\cbsr.b64"
echo AAPQAgACQAcwB0AGEAcgB0AEkAZAB4ACAAKwAgADEAOwAgACQAaQAgAC0AbAB0ACAAJABhAGwAbABMAGkAbgBlAHMALgBDAG8AdQBuAHQAOwAgACQAaQArACsAKQAgAHsACgAgACAAIAAgACAAIAAgACAAaQBmACAAKAAoACQA>>"%TEMP%\cbsr.b64"
echo aQAgAC0AIAAkAHMAdABhAHIAdABJAGQAeAApACAALQBnAHQAIAA2ADAAKQAgAHsAIABiAHIAZQBhAGsAIAB9AAoAIAAgACAAIAAgACAAIAAgACQAbABpAG4AZQAgAD0AIAAkAGEAbABsAEwAaQBuAGUAcwBbACQAaQBdAC4AVA>>"%TEMP%\cbsr.b64"
echo ByAGkAbQAoACkACgAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAGwAaQBuAGUAIAAtAG0AYQB0AGMAaAAgACcAXgBcAC4AKAB0AGUAeAB0AHwAcgBvAGQAYQB0AGEAfABkAGEAdABhAHwAYgBzAHMAKQBcAHMAKwAoAFwAZAAr>>"%TEMP%\cbsr.b64"
echo ACkAXABzACsAXAAoACcAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGsAZQB5ACAAPQAgACQAbQBhAHQAYwBoAGUAcwBbADEAXQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgALQBuAG8AdAAgAC>>"%TEMP%\cbsr.b64"
echo QAcwBpAHoAZQBzAC4AQwBvAG4AdABhAGkAbgBzAEsAZQB5ACgAJABrAGUAeQApACkAIAB7ACAAJABzAGkAegBlAHMAWwAkAGsAZQB5AF0AIAA9ACAAWwBpAG4AdAA2ADQAXQAkAG0AYQB0AGMAaABlAHMAWwAyAF0AIAB9AAoA>>"%TEMP%\cbsr.b64"
echo IAAgACAAIAAgACAAIAAgAH0AIABlAGwAcwBlAGkAZgAgACgAJABsAGkAbgBlACAALQBtAGEAdABjAGgAIAAnAF4AXAAuAGYAcgBlAGUAXwBmAGwAYQBzAGgAXABzACsAKABcAGQAKwApAFwAcwArAFwAKAAnACkAIAB7AAoAIA>>"%TEMP%\cbsr.b64"
echo AgACAAIAAgACAAIAAgACAAIAAgACAAJABoAGEAcwBGAHIAZQBlAEYAbABhAHMAaAAgAD0AIAAkAHQAcgB1AGUACgAgACAAIAAgACAAIAAgACAAfQAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAcwBpAHoAZQBzAC4AQwBv>>"%TEMP%\cbsr.b64"
echo AHUAbgB0ACAALQBnAGUAIAAkAG4AZQBlAGQAZQBkAEsAZQB5AHMALgBDAG8AdQBuAHQAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGUAeAB0AHIAYQArACsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAG>>"%TEMP%\cbsr.b64"
echo YAIAAoACQAZQB4AHQAcgBhACAALQBnAGUAIAAzACAALQBvAHIAIAAkAGgAYQBzAEYAcgBlAGUARgBsAGEAcwBoACkAIAB7ACAAYgByAGUAYQBrACAAfQAKACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAB9AAoAIAAgACAA>>"%TEMP%\cbsr.b64"
echo IAByAGUAdAB1AHIAbgAgAEAAewAgAFMAaQB6AGUAcwAgAD0AIAAkAHMAaQB6AGUAcwA7ACAASABhAHMARgByAGUAZQBGAGwAYQBzAGgAIAA9ACAAJABoAGEAcwBGAHIAZQBlAEYAbABhAHMAaAAgAH0ACgB9AAoACgAkAGgAZQ>>"%TEMP%\cbsr.b64"
echo BhAGQAaQBuAGcASQBuAGQAZQB4AGUAcwAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBDAG8AbABsAGUAYwB0AGkAbwBuAHMALgBHAGUAbgBlAHIAaQBjAC4ATABpAHMAdABbAGkAbgB0AF0ACgBm>>"%TEMP%\cbsr.b64"
echo AG8AcgAgACgAJABpACAAPQAgADAAOwAgACQAaQAgAC0AbAB0ACAAJABsAGkAbgBlAHMALgBDAG8AdQBuAHQAOwAgACQAaQArACsAKQAgAHsACgAgACAAIAAgAGkAZgAgACgAJABsAGkAbgBlAHMAWwAkAGkAXQAuAFQAcgBpAG>>"%TEMP%\cbsr.b64"
echo 0AKAApACAALQBlAHEAIAAiAEYAaQByAG0AdwBhAHIAZQAgAHMAaQB6AGUAIgApACAAewAgACQAaABlAGEAZABpAG4AZwBJAG4AZABlAHgAZQBzAC4AQQBkAGQAKAAkAGkAKQAgAH0ACgB9AAoACgBpAGYAIAAoACQAaABlAGEA>>"%TEMP%\cbsr.b64"
echo ZABpAG4AZwBJAG4AZABlAHgAZQBzAC4AQwBvAHUAbgB0ACAALQBlAHEAIAAwACkAIAB7AAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBDAG8AdQBsAGQAIABuAG8AdAAgAGYAaQBuAGQAIABhACAAJwBGAGkAcg>>"%TEMP%\cbsr.b64"
echo BtAHcAYQByAGUAIABzAGkAegBlACcAIABzAGUAYwB0AGkAbwBuACAAaQBuACAAdABoAGUAIABiAHUAaQBsAGQAIABsAG8AZwAgAC0AIABzAGsAaQBwAHAAaQBuAGcAIAByAGUAcABvAHIAdAAuACIAIAAtAEYAbwByAGUAZwBy>>"%TEMP%\cbsr.b64"
echo AG8AdQBuAGQAQwBvAGwAbwByACAAWQBlAGwAbABvAHcACgAgACAAIAAgAHIAZQB0AHUAcgBuAAoAfQAKAAoAJABzAGkAegBlAHMAIAA9ACAAJABuAHUAbABsAAoAZgBvAHIAZQBhAGMAaAAgACgAJABpAGQAeAAgAGkAbgAgAC>>"%TEMP%\cbsr.b64"
echo QAaABlAGEAZABpAG4AZwBJAG4AZABlAHgAZQBzACkAIAB7AAoAIAAgACAAIAAkAGIAbABvAGMAawAgAD0AIABHAGUAdAAtAFMAaQB6AGUAQgBsAG8AYwBrACAAJABpAGQAeAAgACQAbABpAG4AZQBzACAAJABuAGUAZQBkAGUA>>"%TEMP%\cbsr.b64"
echo ZAAKACAAIAAgACAAaQBmACAAKAAkAGIAbABvAGMAawAuAFMAaQB6AGUAcwAuAEMAbwB1AG4AdAAgAC0AZwBlACAAJABuAGUAZQBkAGUAZAAuAEMAbwB1AG4AdAAgAC0AYQBuAGQAIAAkAGIAbABvAGMAawAuAEgAYQBzAEYAcg>>"%TEMP%\cbsr.b64"
echo BlAGUARgBsAGEAcwBoACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACQAcwBpAHoAZQBzACAAPQAgACQAYgBsAG8AYwBrAC4AUwBpAHoAZQBzAAoAIAAgACAAIAAgACAAIAAgAGIAcgBlAGEAawAKACAAIAAgACAAfQAKAH0ACgBp>>"%TEMP%\cbsr.b64"
echo AGYAIAAoAC0AbgBvAHQAIAAkAHMAaQB6AGUAcwApACAAewAKACAAIAAgACAAZgBvAHIAZQBhAGMAaAAgACgAJABpAGQAeAAgAGkAbgAgACQAaABlAGEAZABpAG4AZwBJAG4AZABlAHgAZQBzACkAIAB7AAoAIAAgACAAIAAgAC>>"%TEMP%\cbsr.b64"
echo AAIAAgACQAYgBsAG8AYwBrACAAPQAgAEcAZQB0AC0AUwBpAHoAZQBCAGwAbwBjAGsAIAAkAGkAZAB4ACAAJABsAGkAbgBlAHMAIAAkAG4AZQBlAGQAZQBkAAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABiAGwAbwBjAGsA>>"%TEMP%\cbsr.b64"
echo LgBTAGkAegBlAHMALgBDAG8AdQBuAHQAIAAtAGcAZQAgACQAbgBlAGUAZABlAGQALgBDAG8AdQBuAHQAKQAgAHsAIAAkAHMAaQB6AGUAcwAgAD0AIAAkAGIAbABvAGMAawAuAFMAaQB6AGUAcwA7ACAAYgByAGUAYQBrACAAfQ>>"%TEMP%\cbsr.b64"
echo AKACAAIAAgACAAfQAKAH0ACgAKAGkAZgAgACgALQBuAG8AdAAgACQAcwBpAHoAZQBzACAALQBvAHIAIAAkAHMAaQB6AGUAcwAuAEMAbwB1AG4AdAAgAC0AbAB0ACAAJABuAGUAZQBkAGUAZAAuAEMAbwB1AG4AdAApACAAewAK>>"%TEMP%\cbsr.b64"
echo ACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAQwBvAHUAbABkACAAbgBvAHQAIABmAGkAbgBkACAAYQAgAGMAbwBtAHAAbABlAHQAZQAgAGYAaQByAG0AdwBhAHIAZQAgAHMAaQB6AGUAIABiAGwAbwBjAGsAIABpAG>>"%TEMP%\cbsr.b64"
echo 4AIAB0AGgAZQAgAGIAdQBpAGwAZAAgAGwAbwBnACAALQAgAHMAawBpAHAAcABpAG4AZwAgAHIAZQBwAG8AcgB0AC4AIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABZAGUAbABsAG8AdwAKACAAIAAgACAA>>"%TEMP%\cbsr.b64"
echo cgBlAHQAdQByAG4ACgB9AAoACgAkAG4AZQB3AFQAZQB4AHQAIAAgACAAPQAgACQAcwBpAHoAZQBzAFsAJwB0AGUAeAB0ACcAXQAKACQAbgBlAHcAUgBvAGQAYQB0AGEAIAA9ACAAJABzAGkAegBlAHMAWwAnAHIAbwBkAGEAdA>>"%TEMP%\cbsr.b64"
echo BhACcAXQAKACQAbgBlAHcARABhAHQAYQAgACAAIAA9ACAAJABzAGkAegBlAHMAWwAnAGQAYQB0AGEAJwBdAAoAJABuAGUAdwBCAHMAcwAgACAAIAAgAD0AIAAkAHMAaQB6AGUAcwBbACcAYgBzAHMAJwBdAAoAIwAgAE8AbgBs>>"%TEMP%\cbsr.b64"
echo AHkAIAAuAHQAZQB4AHQALwAuAHIAbwBkAGEAdABhAC8ALgBkAGEAdABhACAAYQBjAHQAdQBhAGwAbAB5ACAAbwBjAGMAdQBwAHkAIABmAGwAYQBzAGgAIAAtACAALgBiAHMAcwAgAGkAcwAgAFIAQQBNAC0AbwBuAGwAeQAgAG>>"%TEMP%\cbsr.b64"
echo EAbgBkACAAaQBzAAoAIwAgAGUAeABjAGwAdQBkAGUAZAAgAGYAcgBvAG0AIAB0AGgAZQAgAGYAbABhAHMAaAAtAHUAcwBlAGQAIAAvACAAZgByAGUAZQAtAHMAcABhAGMAZQAgAG0AYQB0AGgAIAAoAHMAaABvAHcAbgAgAHMA>>"%TEMP%\cbsr.b64"
echo ZQBwAGEAcgBhAHQAZQBsAHkALAAgAGkAbgBmAG8AIABvAG4AbAB5ACkALgAKACQAbgBlAHcARgBsAGEAcwBoAFUAcwBlAGQAIAA9ACAAJABuAGUAdwBUAGUAeAB0ACAAKwAgACQAbgBlAHcAUgBvAGQAYQB0AGEAIAArACAAJA>>"%TEMP%\cbsr.b64"
echo BuAGUAdwBEAGEAdABhAAoAJABuAGUAdwBGAHIAZQBlACAAIAAgACAAIAAgAD0AIAAkAEMAZQBpAGwAaQBuAGcAIAAtACAAJABuAGUAdwBGAGwAYQBzAGgAVQBzAGUAZAAKAAoAJABwAHIAZQB2ACAAPQAgACQAbgB1AGwAbAAK>>"%TEMP%\cbsr.b64"
echo AGkAZgAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQARABhAHQAYQBGAGkAbABlACkAIAB7AAoAIAAgACAAIAAkAHAAIAA9ACAAQAB7AH0ACgAgACAAIAAgAGYAbwByAGUAYQBjAG>>"%TEMP%\cbsr.b64"
echo gAIAAoACQAbAAgAGkAbgAgACgARwBlAHQALQBDAG8AbgB0AGUAbgB0ACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAEQAYQB0AGEARgBpAGwAZQApACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABsACAA>>"%TEMP%\cbsr.b64"
echo LQBtAGEAdABjAGgAIAAnAF4AKABcAFMAKwApAD0AKAAtAD8AXABkACsAKQAkACcAKQAgAHsAIAAkAHAAWwAkAG0AYQB0AGMAaABlAHMAWwAxAF0AXQAgAD0AIABbAGkAbgB0ADYANABdACQAbQBhAHQAYwBoAGUAcwBbADIAXQ>>"%TEMP%\cbsr.b64"
echo AgAH0ACgAgACAAIAAgAH0ACgAgACAAIAAgAGkAZgAgACgAJABwAC4AQwBvAG4AdABhAGkAbgBzAEsAZQB5ACgAJwB0AGUAeAB0ACcAKQAgAC0AYQBuAGQAIAAkAHAALgBDAG8AbgB0AGEAaQBuAHMASwBlAHkAKAAnAHIAbwBk>>"%TEMP%\cbsr.b64"
echo AGEAdABhACcAKQAgAC0AYQBuAGQAIAAkAHAALgBDAG8AbgB0AGEAaQBuAHMASwBlAHkAKAAnAGQAYQB0AGEAJwApACAALQBhAG4AZAAgACQAcAAuAEMAbwBuAHQAYQBpAG4AcwBLAGUAeQAoACcAYgBzAHMAJwApACkAIAB7AA>>"%TEMP%\cbsr.b64"
echo oAIAAgACAAIAAgACAAIAAgACQAcAByAGUAdgAgAD0AIAAkAHAACgAgACAAIAAgAH0ACgB9AAoACgAkAE0AZQB0AHIAaQBjAFcAaQBkAHQAaAAgAD0AIAAxADIACgAkAEMAbwBsAFcAaQBkAHQAaAAgAD0AIAAzADAACgAkAEIA>>"%TEMP%\cbsr.b64"
echo bwByAGQAZQByAFcAaQBkAHQAaAAgAD0AIAAkAE0AZQB0AHIAaQBjAFcAaQBkAHQAaAAgACsAIAAxACAAKwAgACgAJABDAG8AbABXAGkAZAB0AGgAIAArACAAMQApACAAKgAgADMACgAkAHIAbwB3AEYAbQB0ADQAIAA9ACAAIg>>"%TEMP%\cbsr.b64"
echo B7ADAALAAtACQATQBlAHQAcgBpAGMAVwBpAGQAdABoAH0AIAB7ADEALAAkAEMAbwBsAFcAaQBkAHQAaAB9ACAAewAyACwAJABDAG8AbABXAGkAZAB0AGgAfQAgAHsAMwAsACQAQwBvAGwAVwBpAGQAdABoAH0AIgAKACQAcgBv>>"%TEMP%\cbsr.b64"
echo AHcARgBtAHQAMgAgAD0AIAAiAHsAMAAsAC0AJABNAGUAdAByAGkAYwBXAGkAZAB0AGgAfQAgAHsAMQAsACQAQwBvAGwAVwBpAGQAdABoAH0AIgAKACQAZQBxAEwAaQBuAGUAIAAgAD0AIAAnAD0AJwAgACoAIAAkAEIAbwByAG>>"%TEMP%\cbsr.b64"
echo QAZQByAFcAaQBkAHQAaAAKACQAZABhAHMAaABMAGkAbgBlACAAPQAgACcALQAnACAAKgAgACQAQgBvAHIAZABlAHIAVwBpAGQAdABoAAoACgBmAHUAbgBjAHQAaQBvAG4AIABGAG8AcgBtAGEAdAAtAEMAbwBtAGIAaQBuAGUA>>"%TEMP%\cbsr.b64"
echo ZAAoAFsAaQBuAHQANgA0AF0AJABiAHkAdABlAHMAKQAgAHsACgAgACAAIAAgACQAawBiACAAPQAgACQAYgB5AHQAZQBzACAALwAgADEAMAAyADQACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAKAAnAHsAMAA6AE4AMAB9ACAAYg>>"%TEMP%\cbsr.b64"
echo B5AHQAZQBzACAAKAB7ADEAOgBOADIAfQAgAEsAYgApACcAIAAtAGYAIAAkAGIAeQB0AGUAcwAsACAAJABrAGIAKQAKAH0ACgAKAGYAdQBuAGMAdABpAG8AbgAgAEYAbwByAG0AYQB0AC0AQwBvAG0AYgBpAG4AZQBkAEQAaQBm>>"%TEMP%\cbsr.b64"
echo AGYAKABbAGkAbgB0ADYANABdACQAbwBsAGQAQgB5AHQAZQBzACwAIABbAGkAbgB0ADYANABdACQAbgBlAHcAQgB5AHQAZQBzACkAIAB7AAoAIAAgACAAIAAkAGQAIAA9ACAAJABuAGUAdwBCAHkAdABlAHMAIAAtACAAJABvAG>>"%TEMP%\cbsr.b64"
echo wAZABCAHkAdABlAHMACgAgACAAIAAgACQAZABLAGIAIAA9ACAAJABkACAALwAgADEAMAAyADQACgAgACAAIAAgAGkAZgAgACgAJABkACAALQBnAHQAIAAwACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAA>>"%TEMP%\cbsr.b64"
echo KAAnACsAewAwADoATgAwAH0AIABiAHkAdABlAHMAIAAoACsAewAxADoATgAyAH0AIABLAGIAKQAnACAALQBmACAAJABkACwAIAAkAGQASwBiACkACgAgACAAIAAgAH0ACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAKAAnAHsAMA>>"%TEMP%\cbsr.b64"
echo A6AE4AMAB9ACAAYgB5AHQAZQBzACAAKAB7ADEAOgBOADIAfQAgAEsAYgApACcAIAAtAGYAIAAkAGQALAAgACQAZABLAGIAKQAKAH0ACgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACIACgBXAHIAaQB0AGUALQBIAG8AcwB0>>"%TEMP%\cbsr.b64"
echo ACAAJABlAHEATABpAG4AZQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACAASQBOAFQARQBSAE4AQQBMACAARgBMAEEAUwBIACAAUwBJAFoARQAgAFIARQBQAE8AUgBUACAAKABiAHkAdABlAHMALAAgAHcAaQB0AGgAIABLAE>>"%TEMP%\cbsr.b64"
echo IAIABzAGgAbwB3AG4AIABhAGwAbwBuAGcAcwBpAGQAZQApACIACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAgACgAYwBvAHIAZQAgAGkAbgB0AGUAcgBuAGEAbAAgAGYAaQByAG0AdwBhAHIAZQAgAG8AbgBsAHkAIAAtACAA>>"%TEMP%\cbsr.b64"
echo ZQB4AGMAbAB1AGQAZQBzACAAZQB4AHQAZQByAG4AYQBsACAAYQBwAHAAbABpAGMAYQB0AGkAbwBuAHMALAAgAGUAdABjAC4AKQAiAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACQAZQBxAEwAaQBuAGUACgAKAGkAZgAgACgAJA>>"%TEMP%\cbsr.b64"
echo BwAHIAZQB2ACkAIAB7AAoAIAAgACAAIAAkAHAAcgBlAHYARgBsAGEAcwBoAFUAcwBlAGQAIAA9ACAAJABwAHIAZQB2AFsAJwB0AGUAeAB0ACcAXQAgACsAIAAkAHAAcgBlAHYAWwAnAHIAbwBkAGEAdABhACcAXQAgACsAIAAk>>"%TEMP%\cbsr.b64"
echo AHAAcgBlAHYAWwAnAGQAYQB0AGEAJwBdAAoAIAAgACAAIAAkAHAAcgBlAHYARgByAGUAZQAgACAAIAAgACAAIAA9ACAAJABDAGUAaQBsAGkAbgBnACAALQAgACQAcAByAGUAdgBGAGwAYQBzAGgAVQBzAGUAZAAKAAoAIAAgAC>>"%TEMP%\cbsr.b64"
echo AAIAAkAHIAbwB3AHMAIAA9ACAAQAAoAAoAIAAgACAAIAAgACAAIAAgAFsAcABzAGMAdQBzAHQAbwBtAG8AYgBqAGUAYwB0AF0AQAB7ACAATgBhAG0AZQAgAD0AIAAnAC4AdABlAHgAdAAnADsAIAAgACAAIAAgACAATwBsAGQA>>"%TEMP%\cbsr.b64"
echo IAA9ACAAJABwAHIAZQB2AFsAJwB0AGUAeAB0ACcAXQA7ACAAIAAgAE4AZQB3ACAAPQAgACQAbgBlAHcAVABlAHgAdAAgACAAIAB9AAoAIAAgACAAIAAgACAAIAAgAFsAcABzAGMAdQBzAHQAbwBtAG8AYgBqAGUAYwB0AF0AQA>>"%TEMP%\cbsr.b64"
echo B7ACAATgBhAG0AZQAgAD0AIAAnAC4AcgBvAGQAYQB0AGEAJwA7ACAAIAAgACAATwBsAGQAIAA9ACAAJABwAHIAZQB2AFsAJwByAG8AZABhAHQAYQAnAF0AOwAgAE4AZQB3ACAAPQAgACQAbgBlAHcAUgBvAGQAYQB0AGEAIAB9>>"%TEMP%\cbsr.b64"
echo AAoAIAAgACAAIAAgACAAIAAgAFsAcABzAGMAdQBzAHQAbwBtAG8AYgBqAGUAYwB0AF0AQAB7ACAATgBhAG0AZQAgAD0AIAAnAC4AZABhAHQAYQAnADsAIAAgACAAIAAgACAATwBsAGQAIAA9ACAAJABwAHIAZQB2AFsAJwBkAG>>"%TEMP%\cbsr.b64"
echo EAdABhACcAXQA7ACAAIAAgAE4AZQB3ACAAPQAgACQAbgBlAHcARABhAHQAYQAgACAAIAB9AAoAIAAgACAAIAAgACAAIAAgAFsAcABzAGMAdQBzAHQAbwBtAG8AYgBqAGUAYwB0AF0AQAB7ACAATgBhAG0AZQAgAD0AIAAnAC4A>>"%TEMP%\cbsr.b64"
echo YgBzAHMAIAAoAFIAQQBNACkAJwA7ACAATwBsAGQAIAA9ACAAJABwAHIAZQB2AFsAJwBiAHMAcwAnAF0AOwAgACAAIAAgAE4AZQB3ACAAPQAgACQAbgBlAHcAQgBzAHMAIAAgACAAIAB9AAoAIAAgACAAIAApAAoACgAgACAAIA>>"%TEMP%\cbsr.b64"
echo AgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACQAcgBvAHcARgBtAHQANAAgAC0AZgAgACIATQBlAHQAcgBpAGMAIgAsACAAIgBDAHUAcgByAGUAbgB0ACAAQgB1AGkAbABkACIALAAgACIARABpAGYAZgBlAHIAZQBuAGMAZQAi>>"%TEMP%\cbsr.b64"
echo ACwAIAAiAEwAYQBzAHQAIABCAHUAaQBsAGQAIgApAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAJABkAGEAcwBoAEwAaQBuAGUACgAgACAAIAAgAGYAbwByAGUAYQBjAGgAIAAoACQAcgAgAGkAbgAgACQAcgBvAH>>"%TEMP%\cbsr.b64"
echo cAcwApACAAewAKACAAIAAgACAAIAAgACAAIAAkAG8AbABkAFMAdAByACAAPQAgAEYAbwByAG0AYQB0AC0AQwBvAG0AYgBpAG4AZQBkACAAJAByAC4ATwBsAGQACgAgACAAIAAgACAAIAAgACAAJABuAGUAdwBTAHQAcgAgAD0A>>"%TEMP%\cbsr.b64"
echo IABGAG8AcgBtAGEAdAAtAEMAbwBtAGIAaQBuAGUAZAAgACQAcgAuAE4AZQB3AAoAIAAgACAAIAAgACAAIAAgACQAZABpAGYAZgBTAHQAcgAgAD0AIABGAG8AcgBtAGEAdAAtAEMAbwBtAGIAaQBuAGUAZABEAGkAZgBmACAAJA>>"%TEMP%\cbsr.b64"
echo ByAC4ATwBsAGQAIAAkAHIALgBOAGUAdwAKACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAKAAkAHIAbwB3AEYAbQB0ADQAIAAtAGYAIAAkAHIALgBOAGEAbQBlACwAIAAkAG4AZQB3AFMAdAByACwAIAAk>>"%TEMP%\cbsr.b64"
echo AGQAaQBmAGYAUwB0AHIALAAgACQAbwBsAGQAUwB0AHIAKQAKACAAIAAgACAAfQAKAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAJABlAHEATABpAG4AZQAKACAAIAAgACAAJABmAHIAZQBlAE8AbABkAFMAdAByAC>>"%TEMP%\cbsr.b64"
echo AAPQAgAEYAbwByAG0AYQB0AC0AQwBvAG0AYgBpAG4AZQBkACAAJABwAHIAZQB2AEYAcgBlAGUACgAgACAAIAAgACQAZgByAGUAZQBOAGUAdwBTAHQAcgAgAD0AIABGAG8AcgBtAGEAdAAtAEMAbwBtAGIAaQBuAGUAZAAgACQA>>"%TEMP%\cbsr.b64"
echo bgBlAHcARgByAGUAZQAKACAAIAAgACAAJABmAHIAZQBlAEQAaQBmAGYAUwB0AHIAIAA9ACAARgBvAHIAbQBhAHQALQBDAG8AbQBiAGkAbgBlAGQARABpAGYAZgAgACQAcAByAGUAdgBGAHIAZQBlACAAJABuAGUAdwBGAHIAZQ>>"%TEMP%\cbsr.b64"
echo BlAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAKAAkAHIAbwB3AEYAbQB0ADQAIAAtAGYAIAAiAEYAUgBFAEUAIABTAFAAQQBDAEUAIgAsACAAJABmAHIAZQBlAE4AZQB3AFMAdAByACwAIAAkAGYAcgBlAGUARABp>>"%TEMP%\cbsr.b64"
echo AGYAZgBTAHQAcgAsACAAJABmAHIAZQBlAE8AbABkAFMAdAByACkACgB9ACAAZQBsAHMAZQAgAHsACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAE4AbwAgAHAAcgBlAHYAaQBvAHUAcwAgAGIAdQBpAGwAZAAgAG>>"%TEMP%\cbsr.b64"
echo QAYQB0AGEAIABmAG8AdQBuAGQAIAAtACAAdABoAGkAcwAgAHIAdQBuACAAaQBzACAAdABoAGUAIABuAGUAdwAgAGIAYQBzAGUAbABpAG4AZQAuACIACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACIACgAgACAA>>"%TEMP%\cbsr.b64"
echo IAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACQAcgBvAHcARgBtAHQAMgAgAC0AZgAgACIATQBlAHQAcgBpAGMAIgAsACAAIgBWAGEAbAB1AGUAIgApAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAJABkAGEAcw>>"%TEMP%\cbsr.b64"
echo BoAEwAaQBuAGUACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACQAcgBvAHcARgBtAHQAMgAgAC0AZgAgACIALgB0AGUAeAB0ACIALAAgACgARgBvAHIAbQBhAHQALQBDAG8AbQBiAGkAbgBlAGQAIAAkAG4AZQB3>>"%TEMP%\cbsr.b64"
echo AFQAZQB4AHQAKQApAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAKAAkAHIAbwB3AEYAbQB0ADIAIAAtAGYAIAAiAC4AcgBvAGQAYQB0AGEAIgAsACAAKABGAG8AcgBtAGEAdAAtAEMAbwBtAGIAaQBuAGUAZAAgAC>>"%TEMP%\cbsr.b64"
echo QAbgBlAHcAUgBvAGQAYQB0AGEAKQApAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAKAAkAHIAbwB3AEYAbQB0ADIAIAAtAGYAIAAiAC4AZABhAHQAYQAiACwAIAAoAEYAbwByAG0AYQB0AC0AQwBvAG0AYgBpAG4A>>"%TEMP%\cbsr.b64"
echo ZQBkACAAJABuAGUAdwBEAGEAdABhACkAKQAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACgAJAByAG8AdwBGAG0AdAAyACAALQBmACAAIgAuAGIAcwBzACAAKABSAEEATQApACIALAAgACgARgBvAHIAbQBhAHQALQ>>"%TEMP%\cbsr.b64"
echo BDAG8AbQBiAGkAbgBlAGQAIAAkAG4AZQB3AEIAcwBzACkAKQAKAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAJABlAHEATABpAG4AZQAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACgAJAByAG8AdwBG>>"%TEMP%\cbsr.b64"
echo AG0AdAAyACAALQBmACAAIgBGAFIARQBFACAAUwBQAEEAQwBFACIALAAgACgARgBvAHIAbQBhAHQALQBDAG8AbQBiAGkAbgBlAGQAIAAkAG4AZQB3AEYAcgBlAGUAKQApAAoAfQAKAAoAVwByAGkAdABlAC0ASABvAHMAdAAgAC>>"%TEMP%\cbsr.b64"
echo QAZQBxAEwAaQBuAGUACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAiAAoACgAkAHQAaQBtAGUAcwB0AGEAbQBwACAAPQAgAEcAZQB0AC0ARABhAHQAZQAgAC0ARgBvAHIAbQBhAHQAIAAiAHkAeQB5AHkALQBNAE0ALQBkAGQA>>"%TEMP%\cbsr.b64"
echo IABIAEgAOgBtAG0AOgBzAHMAIgAKACQAbwB1AHQAIAA9ACAAQAAoAAoAIAAgACAAIAAiAEwAYQBzAHQAIABCAHUAaQBsAGQAOgAgACQAdABpAG0AZQBzAHQAYQBtAHAAIgAsAAoAIAAgACAAIAAiAHQAZQB4AHQAPQAkAG4AZQ>>"%TEMP%\cbsr.b64"
echo B3AFQAZQB4AHQAIgAsAAoAIAAgACAAIAAiAHIAbwBkAGEAdABhAD0AJABuAGUAdwBSAG8AZABhAHQAYQAiACwACgAgACAAIAAgACIAZABhAHQAYQA9ACQAbgBlAHcARABhAHQAYQAiACwACgAgACAAIAAgACIAYgBzAHMAPQAk>>"%TEMP%\cbsr.b64"
echo AG4AZQB3AEIAcwBzACIALAAKACAAIAAgACAAIgBGAGwAYQBzAGgAVQBzAGUAZAA9ACQAbgBlAHcARgBsAGEAcwBoAFUAcwBlAGQAIgAsAAoAIAAgACAAIAAiAEYAcgBlAGUAUwBwAGEAYwBlAD0AJABuAGUAdwBGAHIAZQBlAC>>"%TEMP%\cbsr.b64"
echo IACgApAAoAUwBlAHQALQBDAG8AbgB0AGUAbgB0ACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAEQAYQB0AGEARgBpAGwAZQAgAC0AVgBhAGwAdQBlACAAJABvAHUAdAAgAC0ARQBuAGMAbwBkAGkAbgBnACAAVQBUAEYA>>"%TEMP%\cbsr.b64"
echo OAAKAA==>>"%TEMP%\cbsr.b64"
powershell -NoProfile -ExecutionPolicy Bypass -Command "$bp=Join-Path $env:TEMP 'cbsr.b64'; $b=(Get-Content -LiteralPath $bp) -join ''; $bytes=[Convert]::FromBase64String($b); $s=[System.Text.Encoding]::Unicode.GetString($bytes); $t=Join-Path $env:TEMP ('cbsr_' + [guid]::NewGuid().ToString('N') + '.ps1'); Set-Content -LiteralPath $t -Value $s -Encoding UTF8; & $t; Remove-Item -LiteralPath $t -Force -ErrorAction SilentlyContinue"
if exist "%TEMP%\cbsr.b64" del /f /q "%TEMP%\cbsr.b64"
if exist fbt_build_output.tmp.log del /f /q fbt_build_output.tmp.log
exit /b